name: 'Codium PR Agent'
description: 'Summarize, review and suggest improvements for pull requests'
branding:
  icon: 'award'
  color: 'green'
inputs:
  image:
    description: 'The Docker image (defaults to building from Dockerfile)'
    required: false
    default: 'Dockerfile.github_action_dockerhub'
runs:
  using: 'docker'
  image: '${{ inputs.image }}'
